permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]



paginate: 10
paginate_path: ":num"
baseurl: ""



title: "The Trees"
email: "hhlucky@yeah.net"
description: ""
github_username:  "hhlucky"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "hhlucky"



#url: "http://blog.rainyalley.com"
#imgrepo: "http://blog.rainyalley.com/static/img"
url: "http://hhlucky.github.io"
imgrepo: "http://hhlucky.github.io/static/img"

